#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthJournal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="LONELYOUTPOST")]
	public partial class HealthDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRoute(Route instance);
    partial void UpdateRoute(Route instance);
    partial void DeleteRoute(Route instance);
    partial void InsertStat(Stat instance);
    partial void UpdateStat(Stat instance);
    partial void DeleteStat(Stat instance);
    partial void InsertTimeOfDay(TimeOfDay instance);
    partial void UpdateTimeOfDay(TimeOfDay instance);
    partial void DeleteTimeOfDay(TimeOfDay instance);
    partial void InsertActivity(Activity instance);
    partial void UpdateActivity(Activity instance);
    partial void DeleteActivity(Activity instance);
    #endregion
		
		public HealthDataContext() : 
				base(global::HealthJournal.Properties.Settings.Default.LONELYOUTPOSTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HealthDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HealthDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HealthDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HealthDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Route> Routes
		{
			get
			{
				return this.GetTable<Route>();
			}
		}
		
		public System.Data.Linq.Table<Stat> Stats
		{
			get
			{
				return this.GetTable<Stat>();
			}
		}
		
		public System.Data.Linq.Table<Journal> Journals
		{
			get
			{
				return this.GetTable<Journal>();
			}
		}
		
		public System.Data.Linq.Table<TimeOfDay> TimeOfDays
		{
			get
			{
				return this.GetTable<TimeOfDay>();
			}
		}
		
		public System.Data.Linq.Table<Activity> Activities
		{
			get
			{
				return this.GetTable<Activity>();
			}
		}
	}
	
	[Table(Name="Health.Routes")]
	public partial class Route : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Description;
		
		private System.Nullable<double> _Miles;
		
		private System.Nullable<System.TimeSpan> _PersonalBest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnMilesChanging(System.Nullable<double> value);
    partial void OnMilesChanged();
    partial void OnPersonalBestChanging(System.Nullable<System.TimeSpan> value);
    partial void OnPersonalBestChanged();
    #endregion
		
		public Route()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_Miles", DbType="Float")]
		public System.Nullable<double> Miles
		{
			get
			{
				return this._Miles;
			}
			set
			{
				if ((this._Miles != value))
				{
					this.OnMilesChanging(value);
					this.SendPropertyChanging();
					this._Miles = value;
					this.SendPropertyChanged("Miles");
					this.OnMilesChanged();
				}
			}
		}
		
		[Column(Storage="_PersonalBest", DbType="Time")]
		public System.Nullable<System.TimeSpan> PersonalBest
		{
			get
			{
				return this._PersonalBest;
			}
			set
			{
				if ((this._PersonalBest != value))
				{
					this.OnPersonalBestChanging(value);
					this.SendPropertyChanging();
					this._PersonalBest = value;
					this.SendPropertyChanged("PersonalBest");
					this.OnPersonalBestChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="Health.Stats")]
	public partial class Stat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _Date;
		
		private int _TimeOfDayID;
		
		private System.Nullable<double> _Weight;
		
		private System.Nullable<double> _FatRatio;
		
		private System.Nullable<double> _BMI;
		
		private System.Nullable<int> _LSys;
		
		private System.Nullable<int> _LDia;
		
		private System.Nullable<int> _RSys;
		
		private System.Nullable<int> _RDia;
		
		private System.Nullable<int> _HeartRate;
		
		private string _Notes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnTimeOfDayIDChanging(int value);
    partial void OnTimeOfDayIDChanged();
    partial void OnWeightChanging(System.Nullable<double> value);
    partial void OnWeightChanged();
    partial void OnFatRatioChanging(System.Nullable<double> value);
    partial void OnFatRatioChanged();
    partial void OnBMIChanging(System.Nullable<double> value);
    partial void OnBMIChanged();
    partial void OnLSysChanging(System.Nullable<int> value);
    partial void OnLSysChanged();
    partial void OnLDiaChanging(System.Nullable<int> value);
    partial void OnLDiaChanged();
    partial void OnRSysChanging(System.Nullable<int> value);
    partial void OnRSysChanged();
    partial void OnRDiaChanging(System.Nullable<int> value);
    partial void OnRDiaChanged();
    partial void OnHeartRateChanging(System.Nullable<int> value);
    partial void OnHeartRateChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    #endregion
		
		public Stat()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[Column(Storage="_TimeOfDayID", DbType="Int NOT NULL")]
		public int TimeOfDayID
		{
			get
			{
				return this._TimeOfDayID;
			}
			set
			{
				if ((this._TimeOfDayID != value))
				{
					this.OnTimeOfDayIDChanging(value);
					this.SendPropertyChanging();
					this._TimeOfDayID = value;
					this.SendPropertyChanged("TimeOfDayID");
					this.OnTimeOfDayIDChanged();
				}
			}
		}
		
		[Column(Storage="_Weight", DbType="Float")]
		public System.Nullable<double> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[Column(Storage="_FatRatio", DbType="Float")]
		public System.Nullable<double> FatRatio
		{
			get
			{
				return this._FatRatio;
			}
			set
			{
				if ((this._FatRatio != value))
				{
					this.OnFatRatioChanging(value);
					this.SendPropertyChanging();
					this._FatRatio = value;
					this.SendPropertyChanged("FatRatio");
					this.OnFatRatioChanged();
				}
			}
		}
		
		[Column(Storage="_BMI", DbType="Float")]
		public System.Nullable<double> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this.OnBMIChanging(value);
					this.SendPropertyChanging();
					this._BMI = value;
					this.SendPropertyChanged("BMI");
					this.OnBMIChanged();
				}
			}
		}
		
		[Column(Storage="_LSys", DbType="Int")]
		public System.Nullable<int> LSys
		{
			get
			{
				return this._LSys;
			}
			set
			{
				if ((this._LSys != value))
				{
					this.OnLSysChanging(value);
					this.SendPropertyChanging();
					this._LSys = value;
					this.SendPropertyChanged("LSys");
					this.OnLSysChanged();
				}
			}
		}
		
		[Column(Storage="_LDia", DbType="Int")]
		public System.Nullable<int> LDia
		{
			get
			{
				return this._LDia;
			}
			set
			{
				if ((this._LDia != value))
				{
					this.OnLDiaChanging(value);
					this.SendPropertyChanging();
					this._LDia = value;
					this.SendPropertyChanged("LDia");
					this.OnLDiaChanged();
				}
			}
		}
		
		[Column(Storage="_RSys", DbType="Int")]
		public System.Nullable<int> RSys
		{
			get
			{
				return this._RSys;
			}
			set
			{
				if ((this._RSys != value))
				{
					this.OnRSysChanging(value);
					this.SendPropertyChanging();
					this._RSys = value;
					this.SendPropertyChanged("RSys");
					this.OnRSysChanged();
				}
			}
		}
		
		[Column(Storage="_RDia", DbType="Int")]
		public System.Nullable<int> RDia
		{
			get
			{
				return this._RDia;
			}
			set
			{
				if ((this._RDia != value))
				{
					this.OnRDiaChanging(value);
					this.SendPropertyChanging();
					this._RDia = value;
					this.SendPropertyChanged("RDia");
					this.OnRDiaChanged();
				}
			}
		}
		
		[Column(Storage="_HeartRate", DbType="Int")]
		public System.Nullable<int> HeartRate
		{
			get
			{
				return this._HeartRate;
			}
			set
			{
				if ((this._HeartRate != value))
				{
					this.OnHeartRateChanging(value);
					this.SendPropertyChanging();
					this._HeartRate = value;
					this.SendPropertyChanged("HeartRate");
					this.OnHeartRateChanged();
				}
			}
		}
		
		[Column(Storage="_Notes", DbType="NVarChar(50)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="Health.Journal")]
	public partial class Journal
	{
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<float> _Weight;
		
		private System.Nullable<System.DateTime> _Walk;
		
		private System.Nullable<System.DateTime> _Run;
		
		private System.Nullable<System.DateTime> _Direct_Work;
		
		private System.Nullable<System.DateTime> _Direct_Home;
		
		private System.Nullable<float> _FatRatio;
		
		private System.Nullable<float> _BMI;
		
		private System.Nullable<short> _LSys;
		
		private System.Nullable<short> _LDia;
		
		private System.Nullable<short> _HeartRate;
		
		private System.Nullable<short> _RSys;
		
		private System.Nullable<int> _RDia;
		
		private string _Notes;
		
		public Journal()
		{
		}
		
		[Column(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[Column(Storage="_Weight", DbType="Real")]
		public System.Nullable<float> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[Column(Storage="_Walk", DbType="DateTime")]
		public System.Nullable<System.DateTime> Walk
		{
			get
			{
				return this._Walk;
			}
			set
			{
				if ((this._Walk != value))
				{
					this._Walk = value;
				}
			}
		}
		
		[Column(Storage="_Run", DbType="DateTime")]
		public System.Nullable<System.DateTime> Run
		{
			get
			{
				return this._Run;
			}
			set
			{
				if ((this._Run != value))
				{
					this._Run = value;
				}
			}
		}
		
		[Column(Name="[Direct Work]", Storage="_Direct_Work", DbType="DateTime")]
		public System.Nullable<System.DateTime> Direct_Work
		{
			get
			{
				return this._Direct_Work;
			}
			set
			{
				if ((this._Direct_Work != value))
				{
					this._Direct_Work = value;
				}
			}
		}
		
		[Column(Name="[Direct Home]", Storage="_Direct_Home", DbType="DateTime")]
		public System.Nullable<System.DateTime> Direct_Home
		{
			get
			{
				return this._Direct_Home;
			}
			set
			{
				if ((this._Direct_Home != value))
				{
					this._Direct_Home = value;
				}
			}
		}
		
		[Column(Storage="_FatRatio", DbType="Real")]
		public System.Nullable<float> FatRatio
		{
			get
			{
				return this._FatRatio;
			}
			set
			{
				if ((this._FatRatio != value))
				{
					this._FatRatio = value;
				}
			}
		}
		
		[Column(Storage="_BMI", DbType="Real")]
		public System.Nullable<float> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this._BMI = value;
				}
			}
		}
		
		[Column(Storage="_LSys", DbType="SmallInt")]
		public System.Nullable<short> LSys
		{
			get
			{
				return this._LSys;
			}
			set
			{
				if ((this._LSys != value))
				{
					this._LSys = value;
				}
			}
		}
		
		[Column(Storage="_LDia", DbType="SmallInt")]
		public System.Nullable<short> LDia
		{
			get
			{
				return this._LDia;
			}
			set
			{
				if ((this._LDia != value))
				{
					this._LDia = value;
				}
			}
		}
		
		[Column(Storage="_HeartRate", DbType="SmallInt")]
		public System.Nullable<short> HeartRate
		{
			get
			{
				return this._HeartRate;
			}
			set
			{
				if ((this._HeartRate != value))
				{
					this._HeartRate = value;
				}
			}
		}
		
		[Column(Storage="_RSys", DbType="SmallInt")]
		public System.Nullable<short> RSys
		{
			get
			{
				return this._RSys;
			}
			set
			{
				if ((this._RSys != value))
				{
					this._RSys = value;
				}
			}
		}
		
		[Column(Storage="_RDia", DbType="Int")]
		public System.Nullable<int> RDia
		{
			get
			{
				return this._RDia;
			}
			set
			{
				if ((this._RDia != value))
				{
					this._RDia = value;
				}
			}
		}
		
		[Column(Storage="_Notes", DbType="NVarChar(255)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
	}
	
	[Table(Name="Health.TimeOfDay")]
	public partial class TimeOfDay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TimeOfDay()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="Health.Activities")]
	public partial class Activity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _Date;
		
		private int _RouteID;
		
		private System.TimeSpan _Time;
		
		private int _TimeOfDayID;
		
		private string _Notes;
		
		private bool _Walk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnRouteIDChanging(int value);
    partial void OnRouteIDChanged();
    partial void OnTimeChanging(System.TimeSpan value);
    partial void OnTimeChanged();
    partial void OnTimeOfDayIDChanging(int value);
    partial void OnTimeOfDayIDChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnWalkChanging(bool value);
    partial void OnWalkChanged();
    #endregion
		
		public Activity()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[Column(Storage="_RouteID", DbType="Int NOT NULL")]
		public int RouteID
		{
			get
			{
				return this._RouteID;
			}
			set
			{
				if ((this._RouteID != value))
				{
					this.OnRouteIDChanging(value);
					this.SendPropertyChanging();
					this._RouteID = value;
					this.SendPropertyChanged("RouteID");
					this.OnRouteIDChanged();
				}
			}
		}
		
		[Column(Storage="_Time", DbType="Time NOT NULL")]
		public System.TimeSpan Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[Column(Storage="_TimeOfDayID", DbType="Int NOT NULL")]
		public int TimeOfDayID
		{
			get
			{
				return this._TimeOfDayID;
			}
			set
			{
				if ((this._TimeOfDayID != value))
				{
					this.OnTimeOfDayIDChanging(value);
					this.SendPropertyChanging();
					this._TimeOfDayID = value;
					this.SendPropertyChanged("TimeOfDayID");
					this.OnTimeOfDayIDChanged();
				}
			}
		}
		
		[Column(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[Column(Storage="_Walk", DbType="Bit NOT NULL")]
		public bool Walk
		{
			get
			{
				return this._Walk;
			}
			set
			{
				if ((this._Walk != value))
				{
					this.OnWalkChanging(value);
					this.SendPropertyChanging();
					this._Walk = value;
					this.SendPropertyChanged("Walk");
					this.OnWalkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
