namespace B737.Physics
{
    using System.Numerics;
    using B737.Systems.Power;

    public class Thrust : IForce
    {
        private readonly Powerplant powerplant;
        private readonly bool isLeftEngine;
        private readonly Vector3 thrustDirection;
        private readonly Vector3 enginePosition; // relative to aircraft CG

        public Thrust(Powerplant powerplant, bool isLeftEngine, Vector3 enginePosition, Vector3? direction = null)
        {
            this.powerplant = powerplant;
            this.isLeftEngine = isLeftEngine;
            this.enginePosition = enginePosition;
            this.thrustDirection = direction ?? new Vector3(1f, 0f, 0f); // forward
        }

        public Vector3 CalculateForce(AircraftState state)
        {
            double thrustN = isLeftEngine
                ? powerplant.Telemetry.ThrustLeftN
                : powerplant.Telemetry.ThrustRightN;

            return thrustDirection * (float)thrustN;
        }

        /// <summary>
        /// Calculate the torque (moment) generated by thrust about the aircraft CG.
        /// </summary>
        public Vector3 CalculateMoment(AircraftState state)
        {
            Vector3 force = CalculateForce(state);
            // Torque = r × F (cross product)
            return Vector3.Cross(enginePosition, force);
        }
    }
}