//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LonelyOutpostModel", "FK_FoodItems_FoodCategories", "FoodCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(lonelyOutpost.FoodCategory), "FoodItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(lonelyOutpost.FoodItem), true)]
[assembly: EdmRelationshipAttribute("LonelyOutpostModel", "FK_FoodJournal_FoodItems", "FoodItem", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(lonelyOutpost.FoodItem), "FoodJournal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(lonelyOutpost.FoodJournal), true)]

#endregion

namespace lonelyOutpost
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LonelyOutpostEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LonelyOutpostEntities object using the connection string found in the 'LonelyOutpostEntities' section of the application configuration file.
        /// </summary>
        public LonelyOutpostEntities() : base("name=LonelyOutpostEntities", "LonelyOutpostEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LonelyOutpostEntities object.
        /// </summary>
        public LonelyOutpostEntities(string connectionString) : base(connectionString, "LonelyOutpostEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LonelyOutpostEntities object.
        /// </summary>
        public LonelyOutpostEntities(EntityConnection connection) : base(connection, "LonelyOutpostEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<aspnet_Users> aspnet_Users
        {
            get
            {
                if ((_aspnet_Users == null))
                {
                    _aspnet_Users = base.CreateObjectSet<aspnet_Users>("aspnet_Users");
                }
                return _aspnet_Users;
            }
        }
        private ObjectSet<aspnet_Users> _aspnet_Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Statistic> Statistics
        {
            get
            {
                if ((_Statistics == null))
                {
                    _Statistics = base.CreateObjectSet<Statistic>("Statistics");
                }
                return _Statistics;
            }
        }
        private ObjectSet<Statistic> _Statistics;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FoodItem> FoodItems
        {
            get
            {
                if ((_FoodItems == null))
                {
                    _FoodItems = base.CreateObjectSet<FoodItem>("FoodItems");
                }
                return _FoodItems;
            }
        }
        private ObjectSet<FoodItem> _FoodItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FoodCategory> FoodCategories
        {
            get
            {
                if ((_FoodCategories == null))
                {
                    _FoodCategories = base.CreateObjectSet<FoodCategory>("FoodCategories");
                }
                return _FoodCategories;
            }
        }
        private ObjectSet<FoodCategory> _FoodCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FoodJournal> FoodJournals
        {
            get
            {
                if ((_FoodJournals == null))
                {
                    _FoodJournals = base.CreateObjectSet<FoodJournal>("FoodJournals");
                }
                return _FoodJournals;
            }
        }
        private ObjectSet<FoodJournal> _FoodJournals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WordList> WordLists
        {
            get
            {
                if ((_WordLists == null))
                {
                    _WordLists = base.CreateObjectSet<WordList>("WordLists");
                }
                return _WordLists;
            }
        }
        private ObjectSet<WordList> _WordLists;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NewWord> NewWords
        {
            get
            {
                if ((_NewWords == null))
                {
                    _NewWords = base.CreateObjectSet<NewWord>("NewWords");
                }
                return _NewWords;
            }
        }
        private ObjectSet<NewWord> _NewWords;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the aspnet_Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaspnet_Users(aspnet_Users aspnet_Users)
        {
            base.AddObject("aspnet_Users", aspnet_Users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Statistics EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStatistics(Statistic statistic)
        {
            base.AddObject("Statistics", statistic);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FoodItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoodItems(FoodItem foodItem)
        {
            base.AddObject("FoodItems", foodItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FoodCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoodCategories(FoodCategory foodCategory)
        {
            base.AddObject("FoodCategories", foodCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FoodJournals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoodJournals(FoodJournal foodJournal)
        {
            base.AddObject("FoodJournals", foodJournal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WordLists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWordLists(WordList wordList)
        {
            base.AddObject("WordLists", wordList);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NewWords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNewWords(NewWord newWord)
        {
            base.AddObject("NewWords", newWord);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LonelyOutpostModel", Name="aspnet_Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aspnet_Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new aspnet_Users object.
        /// </summary>
        /// <param name="applicationId">Initial value of the ApplicationId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="loweredUserName">Initial value of the LoweredUserName property.</param>
        /// <param name="isAnonymous">Initial value of the IsAnonymous property.</param>
        /// <param name="lastActivityDate">Initial value of the LastActivityDate property.</param>
        public static aspnet_Users Createaspnet_Users(global::System.Guid applicationId, global::System.Guid userId, global::System.String userName, global::System.String loweredUserName, global::System.Boolean isAnonymous, global::System.DateTime lastActivityDate)
        {
            aspnet_Users aspnet_Users = new aspnet_Users();
            aspnet_Users.ApplicationId = applicationId;
            aspnet_Users.UserId = userId;
            aspnet_Users.UserName = userName;
            aspnet_Users.LoweredUserName = loweredUserName;
            aspnet_Users.IsAnonymous = isAnonymous;
            aspnet_Users.LastActivityDate = lastActivityDate;
            return aspnet_Users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ApplicationId
        {
            get
            {
                return _ApplicationId;
            }
            set
            {
                OnApplicationIdChanging(value);
                ReportPropertyChanging("ApplicationId");
                _ApplicationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApplicationId");
                OnApplicationIdChanged();
            }
        }
        private global::System.Guid _ApplicationId;
        partial void OnApplicationIdChanging(global::System.Guid value);
        partial void OnApplicationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoweredUserName
        {
            get
            {
                return _LoweredUserName;
            }
            set
            {
                OnLoweredUserNameChanging(value);
                ReportPropertyChanging("LoweredUserName");
                _LoweredUserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoweredUserName");
                OnLoweredUserNameChanged();
            }
        }
        private global::System.String _LoweredUserName;
        partial void OnLoweredUserNameChanging(global::System.String value);
        partial void OnLoweredUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MobileAlias
        {
            get
            {
                return _MobileAlias;
            }
            set
            {
                OnMobileAliasChanging(value);
                ReportPropertyChanging("MobileAlias");
                _MobileAlias = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MobileAlias");
                OnMobileAliasChanged();
            }
        }
        private global::System.String _MobileAlias;
        partial void OnMobileAliasChanging(global::System.String value);
        partial void OnMobileAliasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAnonymous
        {
            get
            {
                return _IsAnonymous;
            }
            set
            {
                OnIsAnonymousChanging(value);
                ReportPropertyChanging("IsAnonymous");
                _IsAnonymous = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAnonymous");
                OnIsAnonymousChanged();
            }
        }
        private global::System.Boolean _IsAnonymous;
        partial void OnIsAnonymousChanging(global::System.Boolean value);
        partial void OnIsAnonymousChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastActivityDate
        {
            get
            {
                return _LastActivityDate;
            }
            set
            {
                OnLastActivityDateChanging(value);
                ReportPropertyChanging("LastActivityDate");
                _LastActivityDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastActivityDate");
                OnLastActivityDateChanged();
            }
        }
        private global::System.DateTime _LastActivityDate;
        partial void OnLastActivityDateChanging(global::System.DateTime value);
        partial void OnLastActivityDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LonelyOutpostModel", Name="FoodCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FoodCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FoodCategory object.
        /// </summary>
        /// <param name="categoryID">Initial value of the CategoryID property.</param>
        /// <param name="categoryName">Initial value of the CategoryName property.</param>
        public static FoodCategory CreateFoodCategory(global::System.Int32 categoryID, global::System.String categoryName)
        {
            FoodCategory foodCategory = new FoodCategory();
            foodCategory.CategoryID = categoryID;
            foodCategory.CategoryName = categoryName;
            return foodCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                if (_CategoryID != value)
                {
                    OnCategoryIDChanging(value);
                    ReportPropertyChanging("CategoryID");
                    _CategoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryID");
                    OnCategoryIDChanged();
                }
            }
        }
        private global::System.Int32 _CategoryID;
        partial void OnCategoryIDChanging(global::System.Int32 value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LonelyOutpostModel", "FK_FoodItems_FoodCategories", "FoodItem")]
        public EntityCollection<FoodItem> FoodItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FoodItem>("LonelyOutpostModel.FK_FoodItems_FoodCategories", "FoodItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FoodItem>("LonelyOutpostModel.FK_FoodItems_FoodCategories", "FoodItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LonelyOutpostModel", Name="FoodItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FoodItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FoodItem object.
        /// </summary>
        /// <param name="itemID">Initial value of the ItemID property.</param>
        /// <param name="foodName">Initial value of the FoodName property.</param>
        /// <param name="basicAmount">Initial value of the BasicAmount property.</param>
        /// <param name="calories">Initial value of the Calories property.</param>
        /// <param name="category">Initial value of the Category property.</param>
        public static FoodItem CreateFoodItem(global::System.Int32 itemID, global::System.String foodName, global::System.String basicAmount, global::System.Int32 calories, global::System.Int32 category)
        {
            FoodItem foodItem = new FoodItem();
            foodItem.ItemID = itemID;
            foodItem.FoodName = foodName;
            foodItem.BasicAmount = basicAmount;
            foodItem.Calories = calories;
            foodItem.Category = category;
            return foodItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItemID
        {
            get
            {
                return _ItemID;
            }
            set
            {
                if (_ItemID != value)
                {
                    OnItemIDChanging(value);
                    ReportPropertyChanging("ItemID");
                    _ItemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ItemID");
                    OnItemIDChanged();
                }
            }
        }
        private global::System.Int32 _ItemID;
        partial void OnItemIDChanging(global::System.Int32 value);
        partial void OnItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FoodName
        {
            get
            {
                return _FoodName;
            }
            set
            {
                OnFoodNameChanging(value);
                ReportPropertyChanging("FoodName");
                _FoodName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FoodName");
                OnFoodNameChanged();
            }
        }
        private global::System.String _FoodName;
        partial void OnFoodNameChanging(global::System.String value);
        partial void OnFoodNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BasicAmount
        {
            get
            {
                return _BasicAmount;
            }
            set
            {
                OnBasicAmountChanging(value);
                ReportPropertyChanging("BasicAmount");
                _BasicAmount = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BasicAmount");
                OnBasicAmountChanged();
            }
        }
        private global::System.String _BasicAmount;
        partial void OnBasicAmountChanging(global::System.String value);
        partial void OnBasicAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Calories
        {
            get
            {
                return _Calories;
            }
            set
            {
                OnCaloriesChanging(value);
                ReportPropertyChanging("Calories");
                _Calories = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Calories");
                OnCaloriesChanged();
            }
        }
        private global::System.Int32 _Calories;
        partial void OnCaloriesChanging(global::System.Int32 value);
        partial void OnCaloriesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.Int32 _Category;
        partial void OnCategoryChanging(global::System.Int32 value);
        partial void OnCategoryChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LonelyOutpostModel", "FK_FoodItems_FoodCategories", "FoodCategory")]
        public FoodCategory FoodCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FoodCategory>("LonelyOutpostModel.FK_FoodItems_FoodCategories", "FoodCategory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FoodCategory>("LonelyOutpostModel.FK_FoodItems_FoodCategories", "FoodCategory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FoodCategory> FoodCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FoodCategory>("LonelyOutpostModel.FK_FoodItems_FoodCategories", "FoodCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FoodCategory>("LonelyOutpostModel.FK_FoodItems_FoodCategories", "FoodCategory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LonelyOutpostModel", "FK_FoodJournal_FoodItems", "FoodJournal")]
        public EntityCollection<FoodJournal> FoodJournals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FoodJournal>("LonelyOutpostModel.FK_FoodJournal_FoodItems", "FoodJournal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FoodJournal>("LonelyOutpostModel.FK_FoodJournal_FoodItems", "FoodJournal", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LonelyOutpostModel", Name="FoodJournal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FoodJournal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FoodJournal object.
        /// </summary>
        /// <param name="journalID">Initial value of the JournalID property.</param>
        /// <param name="day">Initial value of the Day property.</param>
        /// <param name="itemID">Initial value of the ItemID property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        public static FoodJournal CreateFoodJournal(global::System.Int32 journalID, global::System.DateTime day, global::System.Int32 itemID, global::System.Double quantity)
        {
            FoodJournal foodJournal = new FoodJournal();
            foodJournal.JournalID = journalID;
            foodJournal.Day = day;
            foodJournal.ItemID = itemID;
            foodJournal.Quantity = quantity;
            return foodJournal;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 JournalID
        {
            get
            {
                return _JournalID;
            }
            set
            {
                if (_JournalID != value)
                {
                    OnJournalIDChanging(value);
                    ReportPropertyChanging("JournalID");
                    _JournalID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("JournalID");
                    OnJournalIDChanged();
                }
            }
        }
        private global::System.Int32 _JournalID;
        partial void OnJournalIDChanging(global::System.Int32 value);
        partial void OnJournalIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Day
        {
            get
            {
                return _Day;
            }
            set
            {
                OnDayChanging(value);
                ReportPropertyChanging("Day");
                _Day = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Day");
                OnDayChanged();
            }
        }
        private global::System.DateTime _Day;
        partial void OnDayChanging(global::System.DateTime value);
        partial void OnDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItemID
        {
            get
            {
                return _ItemID;
            }
            set
            {
                OnItemIDChanging(value);
                ReportPropertyChanging("ItemID");
                _ItemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemID");
                OnItemIDChanged();
            }
        }
        private global::System.Int32 _ItemID;
        partial void OnItemIDChanging(global::System.Int32 value);
        partial void OnItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Double _Quantity;
        partial void OnQuantityChanging(global::System.Double value);
        partial void OnQuantityChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LonelyOutpostModel", "FK_FoodJournal_FoodItems", "FoodItem")]
        public FoodItem FoodItem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FoodItem>("LonelyOutpostModel.FK_FoodJournal_FoodItems", "FoodItem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FoodItem>("LonelyOutpostModel.FK_FoodJournal_FoodItems", "FoodItem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FoodItem> FoodItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FoodItem>("LonelyOutpostModel.FK_FoodJournal_FoodItems", "FoodItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FoodItem>("LonelyOutpostModel.FK_FoodJournal_FoodItems", "FoodItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LonelyOutpostModel", Name="NewWord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NewWord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NewWord object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="word">Initial value of the Word property.</param>
        public static NewWord CreateNewWord(global::System.Int32 id, global::System.String word)
        {
            NewWord newWord = new NewWord();
            newWord.ID = id;
            newWord.Word = word;
            return newWord;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Word
        {
            get
            {
                return _Word;
            }
            set
            {
                OnWordChanging(value);
                ReportPropertyChanging("Word");
                _Word = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Word");
                OnWordChanged();
            }
        }
        private global::System.String _Word;
        partial void OnWordChanging(global::System.String value);
        partial void OnWordChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LonelyOutpostModel", Name="Statistic")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Statistic : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Statistic object.
        /// </summary>
        /// <param name="day">Initial value of the Day property.</param>
        /// <param name="weight">Initial value of the Weight property.</param>
        /// <param name="timeMeasured">Initial value of the TimeMeasured property.</param>
        public static Statistic CreateStatistic(global::System.Int32 day, global::System.Double weight, global::System.TimeSpan timeMeasured)
        {
            Statistic statistic = new Statistic();
            statistic.Day = day;
            statistic.Weight = weight;
            statistic.TimeMeasured = timeMeasured;
            return statistic;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Day
        {
            get
            {
                return _Day;
            }
            set
            {
                if (_Day != value)
                {
                    OnDayChanging(value);
                    ReportPropertyChanging("Day");
                    _Day = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Day");
                    OnDayChanged();
                }
            }
        }
        private global::System.Int32 _Day;
        partial void OnDayChanging(global::System.Int32 value);
        partial void OnDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private global::System.Double _Weight;
        partial void OnWeightChanging(global::System.Double value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan TimeMeasured
        {
            get
            {
                return _TimeMeasured;
            }
            set
            {
                OnTimeMeasuredChanging(value);
                ReportPropertyChanging("TimeMeasured");
                _TimeMeasured = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeMeasured");
                OnTimeMeasuredChanged();
            }
        }
        private global::System.TimeSpan _TimeMeasured;
        partial void OnTimeMeasuredChanging(global::System.TimeSpan value);
        partial void OnTimeMeasuredChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LonelyOutpostModel", Name="WordList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WordList : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WordList object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="word">Initial value of the Word property.</param>
        /// <param name="known">Initial value of the Known property.</param>
        public static WordList CreateWordList(global::System.Int32 id, global::System.String word, global::System.Boolean known)
        {
            WordList wordList = new WordList();
            wordList.ID = id;
            wordList.Word = word;
            wordList.Known = known;
            return wordList;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Word
        {
            get
            {
                return _Word;
            }
            set
            {
                OnWordChanging(value);
                ReportPropertyChanging("Word");
                _Word = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Word");
                OnWordChanged();
            }
        }
        private global::System.String _Word;
        partial void OnWordChanging(global::System.String value);
        partial void OnWordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Known
        {
            get
            {
                return _Known;
            }
            set
            {
                OnKnownChanging(value);
                ReportPropertyChanging("Known");
                _Known = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Known");
                OnKnownChanged();
            }
        }
        private global::System.Boolean _Known;
        partial void OnKnownChanging(global::System.Boolean value);
        partial void OnKnownChanged();

        #endregion
    
    }

    #endregion
    
}
